kafka:
  bootstrap-servers: 172.23.238.133:9092
  topic2:
    json2: Question
  topic:
    json: response
    
    
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.23.238.205:8071//eureka/
  instance:
    hostname: localhost
    
spring:
  application:
    name: EvaluatorServices
  kafka:
    consumer:
      group-id: QuestionConsumer
      
server:
  port: 8085