# Port at which the the server will run
server:
  port: 8888
# Setting the path where the properties are stored for each service/app
spring:
  cloud:
    config:
      server:
        native:
           search-locations : classpath:/shared    
# Not using Git, so it is native   
  profiles:
    active : native      