spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: pravalli
    password: Root@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
        
jsa:
  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: jsa-group
    topic: jsa-kafka-topic