eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
  instance:
    hostname: localhost
    
    
kafka:
 bootstrap-servers: 172.23.238.133:9092
 topic:
   json: raju