kafka:
  bootstrap-servers: 172.23.238.133:9092
  topic:
    json: test
    json1: statemanager
    json2: EvaluatedQuestion
server:
  port: 8086

spring:
  application:
    name: StateManager_service