eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://172.23.239.163:8070/eureka/

    
kafka:
 bootstrap-servers: 172.23.238.133:9092
 topic:
   json: raju